name: Run Python script and append output to file

on:
  #schedule:
   # - cron: "0 13 * * *"
  workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  run_python_script:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name : Update Document
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run : |
        git clone  https://kursadaltan:$GH_TOKEN@github.com/kursadaltan/tefas_fon_rsi_takip -b main
        cd tefas_fon_rsi_takip
        git config --global user.email "$GH_EMAIL"
        git config --global user.name kursadaltan
        pip install -r requirements.txt
        python tefas.py >> daily_result.txt
        git add daily_result.txt
        git commit --allow-empty -m "add daily report"
        git push origin main   
